name: .NET

on: [pull_request]

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Hello message
      run: echo "Hello guys"
  build:
     runs-on: ubuntu-latest
     needs: welcome
     steps:
     - uses: actions/checkout@v3
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Restore dependencies
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore
  test:
     runs-on: ubuntu-latest
     needs: build
     steps:
     - uses: actions/checkout@v3
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Test
       run: dotnet test
  publish:
     runs-on: ubuntu-latest
     needs: [welcome, build, test]
     steps:
     - uses: actions/checkout@v3
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
     - name: Publish
       run: dotnet publish
